# redis
spring:
  data:
    redis:
      host: localhost
      port: ${REDIS_OUT_BOUND_PORT}
  main:
    allow-bean-definition-overriding: true
---
# jpa
spring:
  jpa:
    open-in-view: false
---
# application
spring:
  profiles:
    active: dev

---
# jwt
spring:
  auth:
    jwt:
      header: ${JWT_HEADER}
      secretKey: ${JWT_SECRET}
      accessExp: ${JWT_ACCESS_EXP}
      refreshExp: ${JWT_REFRESH_EXP}
      prefix: ${JWT_PREFIX}

---
# mail
spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

---
# oauth 2.0
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${LOCAL_GITHUB_CLIENT_ID}
            client-secret: ${LOCAL_GITHUB_CLIENT_SECRET}

---
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        registerHealthIndicator: true
        slidingWindowSize: 3
        minimumNumberOfCalls: 1
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordFailurePredicate: com.integrated.techhub.resilience4j.circuitbreaker.config.CircuitRecordFailurePredicate
  instances:
    webClientGithubClient:
      baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 6s
        cancelRunningFuture: true