# redis
spring:
  data:
    redis:
      host: localhost
      port: ${REDIS_OUT_BOUND_PORT}

---
# application
spring:
  profiles:
    active: dev

---
# jwt
spring:
  config:
    import: classpath:/jwt-env.properties
  auth:
    jwt:
      header: ${JWT_HEADER}
      secret: ${JWT_SECRET}
      accessExp: ${JWT_ACCESS_EXP}
      refreshExp: ${JWT_REFRESH_EXP}
      prefix: ${JWT_PREFIX}

---
# mail
spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true