GET localhost:8080/pull-requests/ranking/1

###

PUT localhost:8080/pull-requests/sync/mine/1?repoName=jwt-reactoring
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwibWVtYmVySWQiOjEsImV4cCI6MTY5OTc4MDQ3OCwiaWF0IjoxNjk5Nzc4Njc4fQ.me7BufWNXJFILO1zuIGBeCJv-5X0wucMR5NBu4hflkM