PUT localhost:8080/pull-requests/sync/mine?repoName=jwp-dashboard-jdbc
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwibWVtYmVySWQiOjEsImV4cCI6MTY5Njg1MDcxMywiaWF0IjoxNjk2ODQ4OTEzfQ.tT9--wUY8qHWsttfKBXWPQUuzUVp8onoX6pJcRl_vgY